### ISSUE TITLE
수정 보완 요청

### ISSUE THREAD

**Issue by jhonghee** [golangkorea/effective-go#55]
아래 hisotory를 보시고 2016년 8월 이후의 변동사항에 대해 한글번역을 수정 보완해 주시길 바랍니다.

https://github.com/golang/go/commits/master/doc/effective_go.html

**Comment by mingrammer** [comment]
확인 후 시간 날 때 수정 후 PR 날리겠슴다

from ming

**Comment by coma333ryu** [comment]
공식 사이트에는 아직 적용이 안된 부분이 있긴 하군요.. 지원자 없으시면 제가 수정하겠습니다..

2017-10-18 11:43 GMT+09:00 ming <notifications@github.com>:
