### ISSUE TITLE
Contributing Rules 생성

### ISSUE THREAD

**Issue by mingrammer** [golangkorea/effective-go#6]
Contributing Rules에 대한 논의

**Comment by kyungkoo** [comment]
문체나 번역 기본 규칙은 텐서플로우 번역에서 사용하고 있는 규칙이 괜찮아 보입니다.
https://github.com/dyanos/FirstContactWithTensorFlowKr/issues/2

**Comment by mingrammer** [comment]
@kyungkoo 기술 단어장 좋은 것 같네요

**Comment by mingrammer** [comment]
진행 및 감수를 위한 원문 보존 방식 제안

1. 최상단 또는 적절한 위치에 원문 링크를 삽입한다. (해당 챕터)
2. 영문 문단 바로 아래에 번역을 하여 영문/한글이 동시에 보이게 한다.
3. 번역 문서(단일 파일)와 원문 문서(단일 파일)을 따로 둔다. 즉, 번역 문서를 생성하여 따로 게재
4. 모든 영문을 한글로 대체한다. 단, diff를 통해 원문을 볼 수 있게한다. (이 경우 @kyungkoo 님이 제안하신 이슈의 6번룰을 같이 적용)

이후 모든 감수가 끝난 후엔 한글만 남기면 될 것 같습니다.

**Comment by kyungkoo** [comment]
각 챕터 마다 한글로 번역 후 PR 을 보내면 diff 에서 영문 + 한글이 보이니 검수 후에 merge 하는 방법도 괜찮을 것 같습니다.

**Comment by findstar** [comment]
브랜치를 pre-kr 브랜치를 생성해서 영문 + 한글 형태로 번역을 하고 최종에는 kr 브랜치로 정리하는건 어떠신가요?

**Comment by jhonghee** [comment]
API에 대한 언급은 godoc 링크를 걸어줘도 좋을 것 같음.

**Comment by jhonghee** [comment]
https://www.gitbook.com/book/gosudaweb/effective-go-in-korean/edit#/edit/master/GLOSSARY.md

gitbook의 GLOSSAY에 대한 기능은 여기를 참조: https://toolchain.gitbook.com/lexicon.html

단어나 표현 번역의 통일을 위해서 Glossary를 이용할 것을 권장합니다.
